// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string CouponIdvalue { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int CouponDiscount { get; set; }

    public int SalesOrService { get; set; }

    public virtual ICollection<JobDetail> JobDetails { get; set; } = new List<JobDetail>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}