// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class CustomerVehicle
{
    public string VehicleIdentification { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public int CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}