// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class Job
{
    public int JobId { get; set; }

    public DateTime JobDateIn { get; set; }

    public DateTime? JobDateStarted { get; set; }

    public DateTime? JobDateDone { get; set; }

    public DateTime? JobDateOut { get; set; }

    public int EmployeeId { get; set; }

    public decimal ShopRate { get; set; }

    public string VehicleIdentification { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<JobDetail> JobDetails { get; set; } = new List<JobDetail>();

    public virtual CustomerVehicle VehicleIdentificationNavigation { get; set; }
}