// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class JobDetail
{
    public int JobDetailId { get; set; }

    public int JobId { get; set; }

    public string Description { get; set; }

    public decimal JobHours { get; set; }

    public string Comments { get; set; }

    public int? CouponId { get; set; }

    public string StatusCode { get; set; }

    public int? EmployeeId { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Job Job { get; set; }

    public virtual ICollection<JobDetailPart> JobDetailParts { get; set; } = new List<JobDetailPart>();
}