// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class JobDetailPart
{
    public int JobDetailPartId { get; set; }

    public int JobDetailId { get; set; }

    public int PartId { get; set; }

    public short Quantity { get; set; }

    public decimal SellingPrice { get; set; }

    public virtual JobDetail JobDetail { get; set; }

    public virtual Part Part { get; set; }
}