// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class Position
{
    public int PositionId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}