// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class ReceiveOrder
{
    public int ReceiveOrderId { get; set; }

    public int PurchaseOrderId { get; set; }

    public DateTime? ReceiveDate { get; set; }

    public int EmployeeId { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }

    public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; } = new List<ReceiveOrderDetail>();

    public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; } = new List<ReturnedOrderDetail>();
}