// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class ReceiveOrderDetail
{
    public int ReceiveOrderDetailId { get; set; }

    public int ReceiveOrderId { get; set; }

    public int PurchaseOrderDetailId { get; set; }

    public int QuantityReceived { get; set; }

    public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }

    public virtual ReceiveOrder ReceiveOrder { get; set; }
}