// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class ReturnedOrderDetail
{
    public int ReturnedOrderDetailId { get; set; }

    public int ReceiveOrderId { get; set; }

    public int? PurchaseOrderDetailId { get; set; }

    public string ItemDescription { get; set; }

    public int Quantity { get; set; }

    public string Reason { get; set; }

    public string VendorPartNumber { get; set; }

    public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }

    public virtual ReceiveOrder ReceiveOrder { get; set; }
}