// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class SaleDetail
{
    public int SaleDetailId { get; set; }

    public int SaleId { get; set; }

    public int PartId { get; set; }

    public int Quantity { get; set; }

    public decimal SellingPrice { get; set; }

    public virtual Part Part { get; set; }

    public virtual Sale Sale { get; set; }
}