// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class Sale
{
    public int SaleId { get; set; }

    public DateTime SaleDate { get; set; }

    public int EmployeeId { get; set; }

    public decimal TaxAmount { get; set; }

    public decimal SubTotal { get; set; }

    public int? CouponId { get; set; }

    public string PaymentType { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<SaleDetail> SaleDetails { get; set; } = new List<SaleDetail>();

    public virtual ICollection<SaleRefund> SaleRefunds { get; set; } = new List<SaleRefund>();
}