// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class StandardJob
{
    public int StandardJobId { get; set; }

    public string Description { get; set; }

    public decimal StandardHours { get; set; }
}