// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBikeLibrary.Entities;

public partial class UnorderedPurchaseItemCart
{
    public int CartId { get; set; }

    public string Description { get; set; }

    public string VendorPartNumber { get; set; }

    public int Quantity { get; set; }
}